dt: 0.5
num_opt_points: 10
max_velocity: 0.3
max_acceleration: 0.2
resolution: 0.1
size: 3.0
distance_threshold: 0.25
inflation_size: 0.1
min_yaw_ang_diff: 20.0
use_points: true
use_current_start: false
use_down_cam: false
use_goto: true
disable_obstacle_avoid: false
disable_jps: false
jps_always: true
inflate_ring_buffer: false
lookahead_time: 5.5
lookahead_grid_size_width: 3.5
lookahead_grid_size_height: 3.0
lookahead_grid_resolution: 0.3