dt: 0.5
num_opt_points: 8
max_velocity: 0.5
max_acceleration: 0.3
resolution: 0.05
size: 3.0
distance_threshold: 0.15
inflation_size: 0.5
min_yaw_ang_diff: 20.0
use_points: true
use_current_start: false
use_down_cam: false
use_goto: true
disable_obstacle_avoid: false
disable_jps: false
jps_always: true
inflate_ring_buffer: true
lookahead_time: 5.5
lookahead_grid_size_width: 3.5
lookahead_grid_size_height: 2.0
lookahead_grid_resolution: 0.3